# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            ShawnKong
tagline:          Codes Change World! 
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
